JDK_PATH= "/app/openjdk"
LOCAL_MOUNT_PATH= "/mnt/robusta"
JDK_NAME= "openjdk"
JMAP_CMD= "{}/bin/jmap -J-Xshareclasses:nonfatal -histo:live {}"
JSTACK_CMD= "{}/bin/jstack -J-Xshareclasses:nonfatal -l {}"
