apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: java-tools
build:
  artifacts:
  - image: robustadev/java-toolkit
    docker:
      dockerfile: dockerfile
  local:
    push: true
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - test_deployment.yaml


profiles:
- name: apple-m1-dev
  build:
    artifacts:
      - image: robustadev/java-toolkit
        context: .
        custom:
          buildCommand: ./build_on_apple_m1.sh
    local:
      push: true
      concurrency: 0
- name: gcloud-build
  build:
    googleCloudBuild:
        projectId: genuine-flight-317411
    artifacts:
      - image: robustadev/java-toolkit
        context: .
        docker:
          dockerfile: dockerfile
- name: arm
  build:
    artifacts:
      - image: robustadev/java-toolkit
        context: .
        custom:
          buildCommand: ./build_with_arm.sh
    local:
      push: true
      concurrency: 0